services:
    parsedown:
        class: Parsedown
    parsedown_extra:
        class: ParsedownExtra
    jeremyjumeau.bundles.parsedown.twig.extension:
        class: JeremyJumeau\ParsedownBundle\Twig\ParsedownExtension
        arguments: ["@parsedown", "@parsedown_extra"]
        tags:
         - { name: twig.extension }
